### ISSUE TITLE
Cannot bind G keys to F13-F24

### ISSUE THREAD

**Issue by xurei** [nickbclifford/gkeybind#4]
When I try to bind G1 to F13, the program crashes.

Also, a list of compatible keys should be useful in the README :-)

My config :
```
actions:
  g1:
    - keys: F13
  g2:
    - text: You've installed gkeybind correctly!
  g3:
    - text: Modify /etc/gkeybind.yml to set your own bindings.
```

Error message : 
```
Unhandled exception: Missing hash key: 65482 (KeyError)
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
```
